### ISSUE TITLE
low performance with large file 

### ISSUE THREAD

**Issue by aj3423** [dstein64/nvim-scrollview#22]
When opening a log file in 2.2mb with 60000 lines, all scroll operations become very lag, such as mouse scroll, or scroll by some plugins like `psliwka/vim-smoothie`.

Is it possible to improve the performance ?

Thanks.

**Comment by dstein64** [comment]
Thanks for reporting this @aj3423!

I am unable to replicate the issue. I loaded Neovim and used the following command to generate a 2.7M file with 71,851 lines and syntax highlighting automatically applied.
```
:for i in range(6) | $read $VIMRUNTIME/doc/eval.txt | endfor
```

1. Do you have an example file I can use to debug? If the log file you're using has sensitive data, do you have some steps I can use to generate a similar file with different data that would also exhibit the same problem?
2. Are you using the latest version of `nvim-scrollview`? I recently [added](https://github.com/dstein64/nvim-scrollview/pull/21) a few optimizations.
3. Are you using folds? If so does `:let g:scrollview_mode = 'simple'` result in reduced lag?
4. Is there any lag after disabling `nvim-scrollview` with `:ScrollViewDisable`?

**Comment by dstein64** [comment]
@aj3423, I've implemented various updates (f92e342d7349a44fe7e10c2b134dbf5fdf37e927, ae872c5b6ba0fc583dbe758266f2b58b68605069, PR #24) to improve the performance of `nvim-scrollview`.

If the updates help, please ignore the questions in my earlier [comment](https://github.com/dstein64/nvim-scrollview/issues/22#issuecomment-790791329). If the lagging still exists, answers to those questions would be helpful for attempting to address the problem.

**Comment by aj3423** [comment]
@dstein64, 

1. The sample file:
[large_file_scroll_lag.txt.zip](https://github.com/dstein64/nvim-scrollview/files/6089288/large_file_scroll_lag.txt.zip)
2. I just updated and tried the latest version, lag still exists
3. The default `virtual` mode causes lag, I tried `simple` mode and the lag is gone.  *folding* seems to be the cause of lag. I've `set foldmethod=indent` in my vimrc, and there are lots of indented lines in the file. Then I tried remove `set foldmethod=indent`, it doesn't lag anymore. 
4. Yes, after turn off the plugin by `:ScrollViewDisable` the lag is gone.

**Comment by dstein64** [comment]
@aj3423, I can replicate the issue you're encountering. The update merged in PR #27 improves the situation, but does not fully resolve the issue. If the scrolling is still too slow for the documents you're editing, I recommend temporarily setting `g:scrollview_mode = 1`.

**Comment by aj3423** [comment]
Ok. thanks.

**Comment by dstein64** [comment]
As of 15dad14de8f533bcd08749dcb778cdd74f0d5b60, if scrollbar refreshing takes more than 100 milliseconds, subsequent refreshes will use `simple` for the `scrollview_mode`. The time limit can be customized with `g:scrollview_refresh_time`. After the limit is reached and the scrollview mode changes, the behavior can be reset by setting `g:scrollview_refresh_time_exceeded` to 0.

Thanks again for reporting @aj3423! Also, if you're editing files with many folds, I suggest you take a look at the `g:scrollview_nvim_14040_workaround` option if you haven't already. A Neovim memory leak results when floating windows are opened and closed while there are folds, which I've reported in https://github.com/neovim/neovim/issues/14040.
